app:
  name: user-serv
  host: 127.0.0.1
  port: 10010
db:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  name: red_bean_anime
log:
  filename: /tmp/user.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
etcd:
  endpoints:
    43.128.25.218:2379
jwt:
  pemPath: configs/privatekey
  issuer: kkako